# Generated by Django 6.0.6 on 2026-06-06 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StickerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Sticker Issued'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('college_department', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('classification', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('parent', 'Parent')], max_length=20)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('two_wheels', 'Two Wheels'), ('four_wheels', 'Four Wheels'), ('other', 'Other')], max_length=20)),
                ('vehicle_color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('white', 'White'), ('black', 'Black'), ('silver', 'Silver'), ('gray', 'Gray'), ('brown', 'Brown'), ('other', 'Other')], max_length=30)),
                ('is_owner', models.BooleanField(default=True)),
                ('or_cr', models.FileField(upload_to='documents/or_cr/')),
                ('drivers_license', models.FileField(upload_to='documents/license/')),
                ('cor', models.FileField(blank=True, null=True, upload_to='documents/cor/')),
                ('authorization_letter', models.FileField(blank=True, null=True, upload_to='documents/auth/')),
                ('rfid_uid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sticker_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
