# Generated by Django 6.0.6 on 2026-06-16 15:53

import applications.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerapplication',
            name='authorization_letter',
            field=models.FileField(blank=True, null=True, upload_to=applications.utils.upload_auth),
        ),
        migrations.AlterField(
            model_name='stickerapplication',
            name='cor',
            field=models.FileField(blank=True, null=True, upload_to=applications.utils.upload_cor),
        ),
        migrations.AlterField(
            model_name='stickerapplication',
            name='drivers_license',
            field=models.FileField(upload_to=applications.utils.upload_license),
        ),
        migrations.AlterField(
            model_name='stickerapplication',
            name='or_cr',
            field=models.FileField(upload_to=applications.utils.upload_or_cr),
        ),
    ]
