# Generated by Django 5.2.16 on 2026-07-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_stickerapplication_authorization_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerapplication',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
