# Generated by Django 5.2.16 on 2026-07-30 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_stickerapplication_issued_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerapplication',
            name='plate_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stickerapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['rejected', 'expired']), _negated=True), fields=('plate_number',), name='unique_active_plate_number'),
        ),
    ]
