# Generated by Django 5.2.16 on 2026-08-06 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_stickerapplication_plate_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stickerapplication',
            index=models.Index(fields=['status', '-created_at'], name='app_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stickerapplication',
            index=models.Index(fields=['applicant', '-created_at'], name='app_applicant_created_idx'),
        ),
    ]
