# Generated by Django 5.2.16 on 2026-08-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_split_or_cr_into_two_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerapplication',
            name='college_department',
            field=models.CharField(choices=[('College of Arts and Humanities', 'College of Arts and Humanities'), ('College of Business and Accountancy', 'College of Business and Accountancy'), ('College of Criminal Justice Education', 'College of Criminal Justice Education'), ('College of Engineering', 'College of Engineering'), ('College of Architecture', 'College of Architecture'), ('College of Hospitality Management and Tourism', 'College of Hospitality Management and Tourism'), ('College of Nursing and Health Sciences', 'College of Nursing and Health Sciences'), ('College of Sciences', 'College of Sciences'), ('College of Teacher Education', 'College of Teacher Education')], max_length=100),
        ),
    ]
