# Generated by Django 5.2.16 on 2026-09-04 18:48

import applications.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_stickerapplication_college_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerapplication',
            name='photo_2x2',
            field=models.FileField(blank=True, null=True, upload_to=applications.utils.upload_photo_2x2),
        ),
    ]
