# Generated by Django 6.0.4 on 2026-04-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sticker_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('sticker_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_tag', to='sticker_portal.stickerapplication')),
            ],
        ),
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('denied', 'Denied')], max_length=10)),
                ('gate', models.CharField(choices=[('main_gate', 'Main Gate'), ('back_gate', 'Back Gate')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_color', models.CharField(blank=True, max_length=50)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('reason_denied', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rfid_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gate_guard.rfidtag')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
