# Generated by Django 6.0.3 on 2026-04-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_guard', '0002_pendingrfidregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
