# Generated by Django 6.0.3 on 2026-04-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_guard', '0003_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='gate_open',
            field=models.BooleanField(default=False),
        ),
    ]
