# Generated by Django 6.0.3 on 2026-04-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_guard', '0004_systemconfig_gate_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gate_photos/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gate_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gate_guard.gatelog')),
            ],
        ),
    ]
