# Generated by Django 6.0.3 on 2026-04-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_guard', '0005_gatephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatelog',
            name='driver_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gatelog',
            name='plate_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
