# Generated by Django 6.0.3 on 2026-05-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate_guard', '0006_alter_gatelog_driver_name_alter_gatelog_plate_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GatePhoto',
        ),
    ]
