# Generated by Django 6.0.3 on 2026-05-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate_guard', '0007_delete_gatephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='gate_open',
        ),
    ]
