# Generated by Django 6.0.3 on 2026-05-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerapplication',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stickerapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Sticker Issued'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
