# Generated by Django 6.0.3 on 2026-05-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_portal', '0003_availabledate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Sticker Issued'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
