# Generated by Django 6.0.3 on 2026-05-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_portal', '0004_alter_stickerapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type_of_vehicle',
            field=models.CharField(choices=[('two_wheels', 'Two Wheels'), ('four_wheels', 'Four Wheels'), ('other', 'Other (specify)')], default='four_wheels', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('silver', 'Silver'), ('gray', 'Gray'), ('other', 'Other (specify)')], default='silver', max_length=20),
        ),
    ]
