# Generated by Django 6.0.3 on 2026-05-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_portal', '0005_remove_vehicle_model_vehicle_type_of_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerapplication',
            name='college_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stickerapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='stickerapplication',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
