# Generated by Django 6.0.3 on 2026-05-08 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_portal', '0006_stickerapplication_college_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerapplication',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='sticker_portal.vehicle'),
        ),
    ]
