# Generated by Django 6.0.3 on 2026-05-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_portal', '0007_alter_stickerapplication_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
