from django.db import models
from django.conf import settings

class RFIDTag(models.Model):
    """RFID tag associated with an approved sticker application."""
    tag_id = models.CharField(max_length=100, unique=True)
    sticker_application = models.OneToOneField(
        'sticker_portal.StickerApplication',
        on_delete=models.CASCADE,
        related_name='rfid_tag'
    )
    is_active = models.BooleanField(default=True)
    issued_at = models.DateTimeField(auto_now_add=True)
    last_used = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"RFID: {self.tag_id} - {self.sticker_application.vehicle.plate_number}"


class GateLog(models.Model):
    """Entry/exit log generated by ESP32 scans."""
    ACTION_CHOICES = (
        ('entry', 'Entry'),
        ('exit', 'Exit'),
        ('denied', 'Denied'),
    )
    GATE_CHOICES = (
        ('main_gate', 'Main Gate'),
        ('back_gate', 'Back Gate'),
    )

    rfid_tag = models.ForeignKey(RFIDTag, on_delete=models.SET_NULL, null=True, blank=True)
    action = models.CharField(max_length=10, choices=ACTION_CHOICES)
    gate = models.CharField(max_length=20, choices=GATE_CHOICES)
    timestamp = models.DateTimeField()
    driver_name = models.CharField(max_length=100, blank=True)
    vehicle_model = models.CharField(max_length=100, blank=True)
    vehicle_color = models.CharField(max_length=50, blank=True)
    plate_number = models.CharField(max_length=20, blank=True)
    reason_denied = models.CharField(max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f"{self.timestamp} - {self.plate_number} - {self.action}"