# Generated by Django 6.0.6 on 2026-06-06 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('claimed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_uid', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('denied', 'Denied')], max_length=10)),
                ('gate_location', models.CharField(default='Main Gate', max_length=50)),
                ('denial_reason', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_logs', to='applications.stickerapplication')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
