# Generated by Django 6.0.6 on 2026-06-16 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Failed Login Attempt'), ('lockout', 'Account Locked Out'), ('app_submitted', 'Application Submitted'), ('app_approved', 'Application Approved'), ('app_rejected', 'Application Rejected'), ('sticker_issued', 'Sticker Issued'), ('appointment_set', 'Appointment Set'), ('gate_entry', 'Gate Entry'), ('gate_exit', 'Gate Exit'), ('gate_denied', 'Gate Access Denied'), ('window_opened', 'Registration Window Opened'), ('window_closed', 'Registration Window Closed'), ('slot_created', 'Appointment Slot Created')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('target_user', models.CharField(blank=True, max_length=150)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
