# Generated by Django 5.1.9 on 2026-07-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Failed Login Attempt'), ('lockout', 'Account Locked Out'), ('app_submitted', 'Application Submitted'), ('app_approved', 'Application Approved'), ('app_rejected', 'Application Rejected'), ('sticker_issued', 'Sticker Issued'), ('app_expired', 'Sticker Expired'), ('appointment_set', 'Appointment Set'), ('gate_entry', 'Gate Entry'), ('gate_exit', 'Gate Exit'), ('gate_denied', 'Gate Access Denied'), ('window_opened', 'Registration Window Opened'), ('window_closed', 'Registration Window Closed'), ('slot_created', 'Appointment Slot Created')], max_length=30),
        ),
    ]
