# Generated by Django 5.2.16 on 2026-08-06 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_stickerapplication_app_status_created_idx_and_more'),
        ('gate', '0005_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='auditlog_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='gatelog',
            index=models.Index(fields=['-timestamp'], name='gatelog_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='gatelog',
            index=models.Index(fields=['application', '-timestamp'], name='gatelog_app_timestamp_idx'),
        ),
    ]
